name: 'prod-infra-apply'

on:
  workflow_dispatch:

jobs:
  terraform1:
    name: 'Terraform Bootstrap'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/Project-strategy/Project-strategy/Bootstrap/prod

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Validate
      run: terraform validate
        
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}   
        
  terraform2:
    name: 'Infra apply'
    needs: terraform1
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/Project-strategy/Project-strategy/environment/prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}    
      

      - name: Terraform Validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
