name: 'test'

on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:        
  terraform1:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Get Secrets
        id: secretdata1
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: test-role
          method: jwt
          path: test
          tlsSkipVerify: true
          secrets: |
            test/access_key ACCESS_CREDENTIALS
